services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: auxiliary-mattermost-universal-sign-in_server_1
      APP_PORT: 8066
      PROXY_AUTH_WHITELIST: "/sign-in*"

  server:
    image: ghcr.io/rleed/umbrel-mattermost-universal-sign-in:latest
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/usr/src/app/data
